INTENT_GENERAL_QUERY = "general-query"
INTENT_ADDITIONAL_QUERY = "additional-query"
INTENT_GRAPHRAG_QUERY = "graphrag-query"

QUALITY_NORMAL = "normal"
QUALITY_DEFAULT = "default"

EMOTION_NEGATIVE = "负面"

ROUTE_GENERATE_NEGATIVE_REPLY = "generate_negative_reply"
ROUTE_GENERATE_POSITIVE_REPLY = "generate_positive_reply"
ROUTE_GENERATE_DEFAULT_REPLY = "generate_default_reply"

ROUTE_REASON_TOOL_USE = "tool_use"
ROUTE_REASON_QUALITY_DEFAULT = "quality_default"
ROUTE_REASON_NEGATIVE_EMOTION = "negative_emotion"
ROUTE_REASON_POSITIVE_OR_NEUTRAL = "positive_or_neutral"

__all__ = [
    "EMOTION_NEGATIVE",
    "INTENT_ADDITIONAL_QUERY",
    "INTENT_GENERAL_QUERY",
    "INTENT_GRAPHRAG_QUERY",
    "QUALITY_DEFAULT",
    "QUALITY_NORMAL",
    "ROUTE_GENERATE_DEFAULT_REPLY",
    "ROUTE_GENERATE_NEGATIVE_REPLY",
    "ROUTE_GENERATE_POSITIVE_REPLY",
    "ROUTE_REASON_NEGATIVE_EMOTION",
    "ROUTE_REASON_POSITIVE_OR_NEUTRAL",
    "ROUTE_REASON_QUALITY_DEFAULT",
    "ROUTE_REASON_TOOL_USE",
]
