EVENT_ANALYZE_RESULT = "analyze_result"
EVENT_ROUTE_DECISION = "route_decision"
EVENT_ANSWER_VALIDATION = "answer_validation"
EVENT_RAG_INDEX_LIFECYCLE = "rag_index_lifecycle"
EVENT_AGENT_INVOKE_SUCCESS = "agent_invoke_success"
EVENT_AGENT_INVOKE_MODEL_ERROR = "agent_invoke_model_error"
EVENT_AGENT_INVOKE_BUSINESS_ERROR = "agent_invoke_business_error"
EVENT_CONVERSATION_MEMORY_LOADED = "conversation_memory_loaded"
EVENT_CONVERSATION_MEMORY_UPDATED = "conversation_memory_updated"
EVENT_SEMANTIC_CACHE_HIT = "semantic_cache_hit"

__all__ = [
    "EVENT_AGENT_INVOKE_BUSINESS_ERROR",
    "EVENT_AGENT_INVOKE_MODEL_ERROR",
    "EVENT_AGENT_INVOKE_SUCCESS",
    "EVENT_ANALYZE_RESULT",
    "EVENT_ANSWER_VALIDATION",
    "EVENT_CONVERSATION_MEMORY_LOADED",
    "EVENT_CONVERSATION_MEMORY_UPDATED",
    "EVENT_RAG_INDEX_LIFECYCLE",
    "EVENT_ROUTE_DECISION",
    "EVENT_SEMANTIC_CACHE_HIT",
]
